#!/usr/bin/env python3
"""
Plot linkage_runs_log.csv generated by the planar-linkage synthesis code.

Usage:
    python plot_linkage_runs.py linkage_runs_log.csv

Specify an output file:
    python plot_linkage_runs.py linkage_runs_log.csv --output linkage_analysis.png
"""

from __future__ import annotations

import argparse
import csv
import sys
import textwrap
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np


def read_run_log(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, List[str], int]:
    """
    Read bars, RMSE, stride, and topology name from linkage_runs_log.csv.

    Returns:
        bars, rmse_values, stride_values, topology_names, skipped_rows
    """
    required_columns = {
        "bars",
        "topology",
        "run",
        "seed",
        "rmse_mm",
        "stride_mm",
    }

    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)

        if not reader.fieldnames:
            raise ValueError(f"CSV file is empty: {path}")

        missing_columns = required_columns.difference(reader.fieldnames)
        if missing_columns:
            raise ValueError(
                f"{path} is missing required columns: "
                + ", ".join(sorted(missing_columns))
            )

        bars: List[int] = []
        rmse_values: List[float] = []
        stride_values: List[float] = []
        topology_names: List[str] = []
        skipped_rows = 0

        for row_number, row in enumerate(reader, start=2):
            try:
                bar_count = int(row["bars"])
                rmse = float(row["rmse_mm"])
                stride = float(row["stride_mm"])
                topology = str(row["topology"]).strip()

                if not topology:
                    raise ValueError("empty topology name")

                # Failed optimizations may be logged as infinity.
                if not np.isfinite(rmse):
                    skipped_rows += 1
                    continue

                bars.append(bar_count)
                rmse_values.append(rmse)
                stride_values.append(stride)
                topology_names.append(topology)

            except (TypeError, ValueError):
                skipped_rows += 1
                print(
                    f"WARNING: skipped invalid row {row_number}: {row}",
                    file=sys.stderr,
                )

    if not bars:
        raise ValueError(
            f"No valid finite RMSE results were found in {path}."
        )

    return (
        np.asarray(bars, dtype=int),
        np.asarray(rmse_values, dtype=float),
        np.asarray(stride_values, dtype=float),
        topology_names,
        skipped_rows,
    )


def shorten_label(label: str, width: int = 55) -> str:
    """Shorten long topology names for plot labels."""
    return textwrap.shorten(label, width=width, placeholder="...")


def plot_run_log(
    csv_path: Path,
    output_path: Path,
    top_count: int,
) -> None:
    bars, rmse, stride, topologies, skipped_rows = read_run_log(csv_path)

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    # Preserve the order in which mechanism classes first appear.
    unique_bars = list(dict.fromkeys(int(value) for value in bars))
    colors = {
        bar_count: color
        for bar_count, color in zip(
            unique_bars,
            ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"],
        )
    }

    figure, axes = plt.subplots(
        2,
        2,
        figsize=(17, 11),
    )

    rmse_axis = axes[0, 0]
    stride_axis = axes[0, 1]
    best_axis = axes[1, 0]
    summary_axis = axes[1, 1]

    # ----------------------------------------------------------------------
    # Panel 1: RMSE distribution by mechanism class
    # ----------------------------------------------------------------------
    grouped_rmse = [
        rmse[bars == bar_count]
        for bar_count in unique_bars
    ]

    box = rmse_axis.boxplot(
        grouped_rmse,
        tick_labels=[f"{bar_count}-bar" for bar_count in unique_bars],
        showmeans=True,
        patch_artist=True,
    )

    for patch, bar_count in zip(box["boxes"], unique_bars):
        patch.set_facecolor(colors[bar_count])
        patch.set_alpha(0.35)

    # Add individual results so failed or outlier-heavy distributions remain visible.
    rng = np.random.default_rng(7)
    for position, bar_count in enumerate(unique_bars, start=1):
        values = rmse[bars == bar_count]
        jitter = rng.uniform(-0.16, 0.16, size=len(values))

        rmse_axis.scatter(
            np.full(len(values), position) + jitter,
            values,
            color=colors[bar_count],
            edgecolor="black",
            linewidth=0.5,
            s=28,
            alpha=0.85,
            zorder=3,
        )

    rmse_axis.set_ylabel("RMSE (mm)")
    rmse_axis.set_title("RMSE distribution by linkage class")
    rmse_axis.grid(axis="y", alpha=0.3)

    # ----------------------------------------------------------------------
    # Panel 2: Stride versus RMSE
    # ----------------------------------------------------------------------
    finite_stride = np.isfinite(stride)

    for bar_count in unique_bars:
        mask = (bars == bar_count) & finite_stride

        stride_axis.scatter(
            stride[mask],
            rmse[mask],
            s=42,
            color=colors[bar_count],
            edgecolor="black",
            linewidth=0.5,
            alpha=0.82,
            label=f"{bar_count}-bar",
        )

        # Mark the best result in this mechanism class.
        if np.any(mask):
            indices = np.flatnonzero(mask)
            best_index = indices[np.argmin(rmse[mask])]

            stride_axis.scatter(
                stride[best_index],
                rmse[best_index],
                s=130,
                facecolor="none",
                edgecolor="black",
                linewidth=1.8,
                zorder=4,
            )

            stride_axis.annotate(
                f"{rmse[best_index]:.1f} mm",
                xy=(stride[best_index], rmse[best_index]),
                xytext=(7, 7),
                textcoords="offset points",
                fontsize=8,
            )

    stride_axis.set_xlabel("Stride (mm)")
    stride_axis.set_ylabel("RMSE (mm)")
    stride_axis.set_title("Stride versus trajectory error")
    stride_axis.grid(True, alpha=0.3)
    stride_axis.legend()

    # ----------------------------------------------------------------------
    # Panel 3: Best topologies
    # ----------------------------------------------------------------------
    best_indices = np.argsort(rmse)[:top_count]
    best_indices = best_indices[::-1]  # Best value at the top.

    labels = [
        shorten_label(f"{bars[index]}-bar | {topologies[index]}")
        for index in best_indices
    ]
    values = rmse[best_indices]
    bar_colors = [colors[int(bars[index])] for index in best_indices]

    best_axis.barh(
        np.arange(len(best_indices)),
        values,
        color=bar_colors,
        edgecolor="black",
        alpha=0.85,
    )

    best_axis.set_yticks(np.arange(len(best_indices)))
    best_axis.set_yticklabels(labels, fontsize=8)
    best_axis.set_xlabel("RMSE (mm)")
    best_axis.set_title(f"Best {len(best_indices)} topology runs")
    best_axis.grid(axis="x", alpha=0.3)

    for y_position, value in enumerate(values):
        best_axis.text(
            value + max(values) * 0.01,
            y_position,
            f"{value:.2f}",
            va="center",
            fontsize=8,
        )

    # ----------------------------------------------------------------------
    # Panel 4: Numeric summary
    # ----------------------------------------------------------------------
    summary_axis.axis("off")
    summary_axis.set_title("Run summary", pad=12)

    overall_best_index = int(np.argmin(rmse))

    summary_lines = [
        f"CSV file: {csv_path.name}",
        f"Valid runs plotted: {len(rmse)}",
        f"Rows skipped or non-finite: {skipped_rows}",
        "",
        "Best result:",
        f"  Mechanism: {bars[overall_best_index]}-bar",
        f"  RMSE: {rmse[overall_best_index]:.3f} mm",
        (
            f"  Stride: "
            f"{stride[overall_best_index]:.3f} mm"
            if np.isfinite(stride[overall_best_index])
            else "  Stride: n/a"
        ),
        "",
        "Class statistics:",
    ]

    for bar_count in unique_bars:
        mask = bars == bar_count
        class_values = rmse[mask]

        summary_lines.extend(
            [
                f"{bar_count}-bar:",
                f"  runs = {mask.sum()}",
                f"  best = {class_values.min():.3f} mm",
                f"  median = {np.median(class_values):.3f} mm",
                f"  worst = {class_values.max():.3f} mm",
                "",
            ]
        )

    summary_axis.text(
        0.02,
        0.98,
        "\n".join(summary_lines).rstrip(),
        transform=summary_axis.transAxes,
        va="top",
        ha="left",
        family="monospace",
        fontsize=9,
    )

    figure.suptitle("Planar linkage synthesis results", fontsize=15)
    figure.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output_path, dpi=180)
    plt.close(figure)

    print(f"Plot saved to: {output_path.resolve()}")
    print(f"Best result: {bars[overall_best_index]}-bar, "
          f"RMSE {rmse[overall_best_index]:.3f} mm")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Plot linkage_runs_log.csv produced by the synthesis program."
    )

    parser.add_argument(
        "csv_file",
        type=Path,
        help="Path to linkage_runs_log.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("linkage_runs_analysis.png"),
        help="Output PNG path.",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=10,
        help="Number of best topology runs to show.",
    )

    args = parser.parse_args()

    if args.top < 1:
        print("ERROR: --top must be at least 1.", file=sys.stderr)
        return 2

    try:
        plot_run_log(
            csv_path=args.csv_file,
            output_path=args.output,
            top_count=args.top,
        )
    except (OSError, ValueError) as exc:
        print(f"PLOT ERROR: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())