#!/usr/bin/env python3
"""
Plot the two CSV outputs generated by walking_linkage_checked.py.

Usage:
    python plot_walking_csv_outputs.py \
        walking_linkage_run_summary.csv \
        walking_linkage_pointwise_errors.csv

Optional output:
    python plot_walking_csv_outputs.py \
        walking_linkage_run_summary.csv \
        walking_linkage_pointwise_errors.csv \
        --output walking_results.png
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np


def read_summary_csv(path: Path) -> List[Dict[str, float | str]]:
    """Read mechanism-level RMSE and maximum-error information."""
    with path.open("r", newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    if not rows:
        raise ValueError(f"Summary CSV contains no rows: {path}")

    plotted_rows: List[Dict[str, float | str]] = []

    for row in rows:
        try:
            rmse = float(row["rmse_mm"])
            max_error = float(row["max_error_mm"])
        except (KeyError, TypeError, ValueError):
            # Failed or skipped stages do not have valid numeric errors.
            continue

        plotted_rows.append(
            {
                "stage": row.get("stage", "Unknown"),
                "status": row.get("status", ""),
                "rmse_mm": rmse,
                "max_error_mm": max_error,
            }
        )

    if not plotted_rows:
        raise ValueError(
            f"No numeric RMSE/max-error rows were found in {path}."
        )

    return plotted_rows


def read_pointwise_csv(
    path: Path,
) -> Tuple[np.ndarray, Dict[str, np.ndarray]]:
    """Read theta and every mechanism error column."""
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)

        if not reader.fieldnames or "theta_deg" not in reader.fieldnames:
            raise ValueError(
                f"{path} must contain a theta_deg column."
            )

        error_names = [
            name for name in reader.fieldnames if name != "theta_deg"
        ]

        theta_values: List[float] = []
        error_values: Dict[str, List[float]] = {
            name: [] for name in error_names
        }

        for row in reader:
            try:
                theta_values.append(float(row["theta_deg"]))
            except (TypeError, ValueError):
                continue

            for name in error_names:
                try:
                    error_values[name].append(float(row[name]))
                except (TypeError, ValueError):
                    error_values[name].append(np.nan)

    if not theta_values:
        raise ValueError(
            f"No valid numeric theta values were found in {path}."
        )

    theta = np.asarray(theta_values, dtype=float)

    series = {
        name: np.asarray(values, dtype=float)
        for name, values in error_values.items()
        if len(values) == len(theta_values)
    }

    if not series:
        raise ValueError(
            f"No valid mechanism error columns were found in {path}."
        )

    return theta, series


def plot_outputs(
    summary_path: Path,
    pointwise_path: Path,
    output_path: Path,
) -> None:
    summary_rows = read_summary_csv(summary_path)
    theta, error_series = read_pointwise_csv(pointwise_path)

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    figure, (summary_axis, error_axis) = plt.subplots(
        1,
        2,
        figsize=(15, 6),
    )

    # --------------------------------------------------------------
    # Left panel: summary RMSE and maximum pointwise error
    # --------------------------------------------------------------
    stages = [str(row["stage"]) for row in summary_rows]
    rmse_values = [float(row["rmse_mm"]) for row in summary_rows]
    max_error_values = [
        float(row["max_error_mm"]) for row in summary_rows
    ]

    positions = np.arange(len(stages))
    bar_width = 0.36

    rmse_bars = summary_axis.bar(
        positions - bar_width / 2,
        rmse_values,
        bar_width,
        label="RMSE",
        color="#1f77b4",
    )

    max_error_bars = summary_axis.bar(
        positions + bar_width / 2,
        max_error_values,
        bar_width,
        label="Maximum error",
        color="#d62728",
    )

    summary_axis.bar_label(rmse_bars, fmt="%.2f", padding=3)
    summary_axis.bar_label(max_error_bars, fmt="%.2f", padding=3)

    summary_axis.set_xticks(positions)
    summary_axis.set_xticklabels(stages, rotation=15, ha="right")
    summary_axis.set_ylabel("Error (mm)")
    summary_axis.set_title("Mechanism run summary")
    summary_axis.grid(axis="y", alpha=0.3)
    summary_axis.legend()

    # --------------------------------------------------------------
    # Right panel: pointwise error at every crank angle
    # --------------------------------------------------------------
    for column_name, errors in error_series.items():
        label = (
            column_name
            .replace("_error_mm", "")
            .replace("_", " ")
            .title()
        )
        error_axis.plot(
            theta,
            errors,
            linewidth=1.4,
            label=label,
        )

    error_axis.set_xlabel("Crank angle (deg)")
    error_axis.set_ylabel("Pointwise foot-tip error (mm)")
    error_axis.set_title("Error at each crank angle")
    error_axis.set_xlim(0, 360)
    error_axis.grid(True, alpha=0.3)
    error_axis.legend()

    figure.suptitle("Walking-linkage validation results")
    figure.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output_path, dpi=180)
    plt.close(figure)

    print(f"Plot saved to: {output_path.resolve()}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Plot walking-linkage summary and pointwise-error CSV files."
        )
    )

    parser.add_argument(
        "summary_csv",
        type=Path,
        help="Path to walking_linkage_run_summary.csv",
    )
    parser.add_argument(
        "pointwise_csv",
        type=Path,
        help="Path to walking_linkage_pointwise_errors.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("walking_linkage_results.png"),
        help="Output PNG path.",
    )

    args = parser.parse_args()

    try:
        plot_outputs(
            summary_path=args.summary_csv,
            pointwise_path=args.pointwise_csv,
            output_path=args.output,
        )
    except (OSError, ValueError) as exc:
        print(f"PLOT ERROR: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())